"""
12 Canonical Event Definitions for QSX-AOS ONE.

These are the immutable contracts that define the entire decision pipeline:

1. MarketDataReceived - Raw market data from exchange
2. FeatureCalculated - Computed features from market data
3. RegimeDetected - Market regime classification
4. AlphaGenerated - Alpha signal generated by swarm/registry
5. SignalGenerated - Trading signal ready for execution
6. RiskCheckRequested - Signal sent to Risk Governor
7. RiskApproved - Risk Governor approves execution
8. RiskRejected - Risk Governor vetoes execution
9. SimulatedOrderSubmitted - Paper order submitted
10. PaperFill - Simulated order filled
11. PositionUpdated - Portfolio position updated
12. PnLUpdated - P&L recalculated
+ HealthStatusChanged - System health status change (audit event)
"""

from typing import Dict, Any, Optional, List
from enum import Enum


# ============================================================================
# Event Type Enums
# ============================================================================

class RiskStatus(Enum):
    """Risk assessment status."""
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class RegimeType(Enum):
    """Market regime classification."""
    BULL = "BULL"
    BEAR = "BEAR"
    SIDEWAYS = "SIDEWAYS"
    TRANSITION = "TRANSITION"


class HealthStatus(Enum):
    """Component health status."""
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"


# ============================================================================
# 1. MARKET DATA RECEIVED
# ============================================================================

MARKET_DATA_RECEIVED_SCHEMA = {
    "symbol": str,
    "exchange": str,
    "timestamp_exchange": str,
    "ohlcv": {
        "open": float,
        "high": float,
        "low": float,
        "close": float,
        "volume": float,
        "turnover": float,
    },
    "bid_ask": {
        "bid": float,
        "ask": float,
        "bid_size": float,
        "ask_size": float,
    },
    "data_quality": {
        "completeness": float,
        "staleness_ms": int,
        "packet_loss": float,
        "latency_p95_ms": int,
    },
    "sequence": int,
}


# ============================================================================
# 2. FEATURE CALCULATED
# ============================================================================

FEATURE_CALCULATED_SCHEMA = {
    "symbol": str,
    "feature_set_id": str,
    "feature_version": str,
    "calculation_timestamp": str,
    "source_event_id": str,
    "lookback_periods": {
        "sma_20": float,
        "sma_50": float,
        "ema_12": float,
        "rsi_14": float,
        "macd": float,
        "bollinger_upper": float,
        "bollinger_lower": float,
        "volatility_30d": float,
        "returns_1h": float,
        "returns_4h": float,
    },
    "quality_flags": {
        "no_lookahead": bool,
        "sufficient_history": bool,
        "all_indicators_computed": bool,
    },
}


# ============================================================================
# 3. REGIME DETECTED
# ============================================================================

REGIME_DETECTED_SCHEMA = {
    "symbol": str,
    "regime": str,
    "regime_score": float,
    "confidence": float,
    "indicators": {
        "trend": str,
        "trend_strength": float,
        "volatility": str,
        "mean_reversion": bool,
        "momentum": float,
    },
    "transition": {
        "previous_regime": str,
        "change_timestamp": str,
        "duration_seconds": int,
    },
}


# ============================================================================
# 4. ALPHA GENERATED
# ============================================================================

ALPHA_GENERATED_SCHEMA = {
    "alpha_id": str,
    "alpha_version": str,
    "model_type": str,
    "models_active": list,
    "signal_direction": str,
    "confidence": float,
    "expected_return": float,
    "validation": {
        "walk_forward_sharpe": float,
        "max_drawdown": float,
        "leakage_detected": bool,
        "monte_carlo_pass": bool,
        "out_of_sample_return": float,
    },
    "market_conditions": {
        "regime": str,
        "volatility": float,
        "applicable_symbols": list,
    },
    "lifecycle": {
        "status": str,
        "promotion_date": Optional[str],
        "demotion_date": Optional[str],
    },
}


# ============================================================================
# 5. SIGNAL GENERATED
# ============================================================================

SIGNAL_GENERATED_SCHEMA = {
    "symbol": str,
    "signal_id": str,
    "signal_type": str,
    "magnitude": float,
    "entry_price": float,
    "stop_loss": float,
    "take_profit": float,
    "position_size_pct": float,
    "reason": str,
    "alpha_contributing": list,
    "confidence": float,
    "expiration": str,
}


# ============================================================================
# 6. RISK CHECK REQUESTED
# ============================================================================

RISK_CHECK_REQUESTED_SCHEMA = {
    "symbol": str,
    "signal_id": str,
    "risk_check_id": str,
    "signal_details": dict,
    "portfolio_state": {
        "current_exposure": float,
        "concentration": str,
        "correlation_risk": str,
        "max_drawdown_pct": float,
        "current_pnl": float,
    },
    "limits": {
        "max_single_position": float,
        "max_sector_exposure": float,
        "max_correlation_to_portfolio": float,
        "max_drawdown_limit": float,
    },
}


# ============================================================================
# 7. RISK APPROVED
# ============================================================================

RISK_APPROVED_SCHEMA = {
    "risk_check_id": str,
    "signal_id": str,
    "approval_timestamp": str,
    "reason": str,
    "risk_score": int,
    "risk_level": str,
    "conditions": {
        "max_position_size": float,
        "required_stop_loss": float,
        "monitoring": str,
    },
}


# ============================================================================
# 8. RISK REJECTED
# ============================================================================

RISK_REJECTED_SCHEMA = {
    "risk_check_id": str,
    "signal_id": str,
    "rejection_timestamp": str,
    "reason": str,
    "risk_score": int,
    "risk_level": str,
    "violated_limits": list,
}


# ============================================================================
# 9. SIMULATED ORDER SUBMITTED
# ============================================================================

SIMULATED_ORDER_SUBMITTED_SCHEMA = {
    "order_id": str,
    "symbol": str,
    "signal_id": str,
    "order_type": str,
    "side": str,
    "quantity": float,
    "price": float,
    "timestamp_submitted": str,
    "execution_mode": str,
    "slippage_assumption": float,
}


# ============================================================================
# 10. PAPER FILL
# ============================================================================

PAPER_FILL_SCHEMA = {
    "order_id": str,
    "fill_id": str,
    "symbol": str,
    "side": str,
    "quantity": float,
    "fill_price": float,
    "fill_timestamp": str,
    "slippage": float,
    "commission": float,
    "total_cost": float,
    "status": str,
}


# ============================================================================
# 11. POSITION UPDATED
# ============================================================================

POSITION_UPDATED_SCHEMA = {
    "position_id": str,
    "symbol": str,
    "quantity": float,
    "entry_price": float,
    "entry_timestamp": str,
    "current_price": float,
    "current_value": float,
    "unrealized_pnl": float,
    "unrealized_pnl_pct": float,
    "status": str,
    "portfolio_weight": float,
    "stop_loss": float,
    "take_profit": float,
}


# ============================================================================
# 12. PNL UPDATED
# ============================================================================

PNL_UPDATED_SCHEMA = {
    "portfolio_id": str,
    "timestamp": str,
    "summary": {
        "total_value": float,
        "cash": float,
        "positions_value": float,
        "positions_count": int,
    },
    "realized_pnl": float,
    "unrealized_pnl": float,
    "total_pnl": float,
    "total_pnl_pct": float,
    "drawdown_pct": float,
    "positions": list,
}


# ============================================================================
# 13. HEALTH STATUS CHANGED
# ============================================================================

HEALTH_STATUS_CHANGED_SCHEMA = {
    "component": str,
    "previous_status": str,
    "status": str,
    "severity": str,
    "timestamp": str,
    "reason": str,
    "metrics": dict,
    "recovery_actions": list,
}


# ============================================================================
# Event Registry
# ============================================================================

CANONICAL_EVENTS = {
    "MarketDataReceived": {
        "schema": MARKET_DATA_RECEIVED_SCHEMA,
        "description": "Raw market data from exchange",
        "source": "exchange_*",
    },
    "FeatureCalculated": {
        "schema": FEATURE_CALCULATED_SCHEMA,
        "description": "Computed features from market data",
        "source": "feature_engine",
    },
    "RegimeDetected": {
        "schema": REGIME_DETECTED_SCHEMA,
        "description": "Market regime classification",
        "source": "regime_engine",
    },
    "AlphaGenerated": {
        "schema": ALPHA_GENERATED_SCHEMA,
        "description": "Alpha signal generated by swarm",
        "source": "alpha_swarm",
    },
    "SignalGenerated": {
        "schema": SIGNAL_GENERATED_SCHEMA,
        "description": "Trading signal ready for execution",
        "source": "signal_engine",
    },
    "RiskCheckRequested": {
        "schema": RISK_CHECK_REQUESTED_SCHEMA,
        "description": "Signal sent to Risk Governor",
        "source": "portfolio_brain",
    },
    "RiskApproved": {
        "schema": RISK_APPROVED_SCHEMA,
        "description": "Risk Governor approves execution",
        "source": "risk_governor",
    },
    "RiskRejected": {
        "schema": RISK_REJECTED_SCHEMA,
        "description": "Risk Governor vetoes execution",
        "source": "risk_governor",
    },
    "SimulatedOrderSubmitted": {
        "schema": SIMULATED_ORDER_SUBMITTED_SCHEMA,
        "description": "Paper order submitted",
        "source": "paper_execution",
    },
    "PaperFill": {
        "schema": PAPER_FILL_SCHEMA,
        "description": "Simulated order filled",
        "source": "paper_execution",
    },
    "PositionUpdated": {
        "schema": POSITION_UPDATED_SCHEMA,
        "description": "Portfolio position updated",
        "source": "execution_state",
    },
    "PnLUpdated": {
        "schema": PNL_UPDATED_SCHEMA,
        "description": "Portfolio P&L recalculated",
        "source": "portfolio_state",
    },
    "HealthStatusChanged": {
        "schema": HEALTH_STATUS_CHANGED_SCHEMA,
        "description": "System component health status change",
        "source": "health_monitor",
    },
}


def get_event_schema(event_type: str) -> Optional[Dict[str, Any]]:
    """Get the schema for a canonical event."""
    event = CANONICAL_EVENTS.get(event_type)
    return event.get("schema") if event else None


def is_canonical_event(event_type: str) -> bool:
    """Check if event type is canonical."""
    return event_type in CANONICAL_EVENTS


def list_canonical_events() -> List[str]:
    """List all canonical event types."""
    return list(CANONICAL_EVENTS.keys())


def get_canonical_event_info(event_type: str) -> Optional[Dict[str, Any]]:
    """Get full info about a canonical event."""
    return CANONICAL_EVENTS.get(event_type)
